/*

 DISPLAY.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 3
   Tile set      : Z:\Users\biggio\Desktop\chiptune\strumentazione\pewpew_gameboy\tools\font.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define displayWidth 20
#define displayHeight 3
#define displayBank 0

unsigned char display[] =
{
  0x8C,0xCC,0xCC,0xCC,0xCC,0xCC,0xCC,0xCC,0xCC,
  0xC9,0xF7,0x77,0x77,0x77,0x77,0x77
};

/* End of DISPLAY.C */
